import{i as n,S as d}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function f(o){const s="https://pixabay.com/api/",r=new URLSearchParams({key:"43018302-cdfd5f670eb7813c2554bba0c",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),a=`${s}?${r}`;return fetch(a).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function g(o){if(o.length==0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}else{const s=o.map(r=>`<li class="gallery-item">
            <a class="photos-list-link" href="${r.largeImageURL}">
            <img class="image" src="${r.webformatURL}" alt="${r.tags}"/>
            </a>
            <ul class="list-container">
            <li class="item-container"><p><span class="title">Likes</span></br>${r.likes}</p></li>
            <li class="item-container"><p><span class="title">Views</span></br>${r.views}</p></li>
            <li class="item-container"><p><span class="title">Comments</span></br>${r.comments}</p></li>
            <li class="item-container"><p><span class="title">Downloads</span></br>${r.downloads}</p></li>
            </ul>
            </li>`).join("");m.insertAdjacentHTML("beforeend",s),h.refresh()}}const l=document.querySelector(".search-form"),u=document.querySelector(".search-input");u.value.trim();const m=document.querySelector(".gallery"),h=new d(".gallery a",{captionDelay:250,captionsData:"alt"}),p=document.querySelector(".loader");p.style.display="none";const c=()=>{p.style.display="none"};l.addEventListener("submit",o=>{o.preventDefault(),m.innerHTML="";const s=u.value.trim();s!==""?(f(s).then(r=>{g(r.hits),c()}).catch(r=>{console.log(r),c(),n.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}),l.reset()):n.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
