import{i,S as u}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();function d(s){const r="https://pixabay.com/api/",t=new URLSearchParams({key:"43018302-cdfd5f670eb7813c2554bba0c",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),n=`${r}?${t}`;return fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function f(s){if(s.length==0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}else{const r=s.map(t=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${t.largeImageURL}">
            <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
            </ul>
            </li>`).join("");return p.insertAdjacentHTML("beforeend",r),h.refresh(),r}}const c=document.querySelector(".search-form"),p=document.querySelector(".gallery"),h=new u(".gallery a",{captionDelay:250,captionsData:"alt"}),m=document.querySelector(".loader");m.style.display="none";const l=()=>{m.style.display="none"};c.addEventListener("submit",s=>{s.preventDefault(),p.innerHTML="";const r=s.target.elements.search.value.trim();r!==""?(d(r).then(t=>{f(t.hits),l()}).catch(t=>{console.log(t),l(),i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}),c.reset()):i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
